def input_to_map(input_str):
    input_list = input_str.split("\n")
    voices = {}
    last_lang = None
    last_locale = None
    voicesTemp = []
    for item in input_list:
        if item == "":
            continue
        locale = item.split()[0]
        if len(locale) > 7:
            locale = locale.split("-")[0] + "-" + locale.split("-")[1]
        if last_locale == locale:
            voice = item.split(locale + "-")[1].split()[0].strip()
            voicesTemp.append(voice)
        else:
            if last_locale is not None:
                voices[last_lang]["voices"] = voicesTemp
            voicesTemp = []
            last_locale = locale
            print(item)
            language, voice = item.split(locale + "-")
            language = language.split()[1:]
            language = " ".join(language).strip()
            last_lang = language
            voice = voice.split(' ')[0].strip()
            if language not in voices:
                voices[language] = {
                    "locale": locale,
                    "voices": []
                }
            voicesTemp.append(voice)
    return voices


input_str = """af-ZA Afrikaans (South Africa) af-ZA-AdriNeural2 (Female)
af-ZA-WillemNeural2 (Male)
am-ET Amharic (Ethiopia) am-ET-AmehaNeural2 (Male)
am-ET-MekdesNeural2 (Female)
ar-AE Arabic (United Arab Emirates) ar-AE-FatimaNeural (Female)
ar-AE-HamdanNeural (Male)
ar-BH Arabic (Bahrain) ar-BH-AliNeural (Male)
ar-BH-LailaNeural (Female)
ar-DZ Arabic (Algeria) ar-DZ-AminaNeural (Female)
ar-DZ-IsmaelNeural (Male)
ar-EG Arabic (Egypt) ar-EG-SalmaNeural (Female)
ar-EG-ShakirNeural (Male)
ar-IQ Arabic (Iraq) ar-IQ-BasselNeural (Male)
ar-IQ-RanaNeural (Female)
ar-JO Arabic (Jordan) ar-JO-SanaNeural (Female)
ar-JO-TaimNeural (Male)
ar-KW Arabic (Kuwait) ar-KW-FahedNeural (Male)
ar-KW-NouraNeural (Female)
ar-LB Arabic (Lebanon) ar-LB-LaylaNeural (Female)
ar-LB-RamiNeural (Male)
ar-LY Arabic (Libya) ar-LY-ImanNeural (Female)
ar-LY-OmarNeural (Male)
ar-MA Arabic (Morocco) ar-MA-JamalNeural (Male)
ar-MA-MounaNeural (Female)
ar-OM Arabic (Oman) ar-OM-AbdullahNeural (Male)
ar-OM-AyshaNeural (Female)
ar-QA Arabic (Qatar) ar-QA-AmalNeural (Female)
ar-QA-MoazNeural (Male)
ar-SA Arabic (Saudi Arabia) ar-SA-HamedNeural (Male)
ar-SA-ZariyahNeural (Female)
ar-SY Arabic (Syria) ar-SY-AmanyNeural (Female)
ar-SY-LaithNeural (Male)
ar-TN Arabic (Tunisia) ar-TN-HediNeural (Male)
ar-TN-ReemNeural (Female)
ar-YE Arabic (Yemen) ar-YE-MaryamNeural (Female)
ar-YE-SalehNeural (Male)
az-AZ Azerbaijani (Latin, Azerbaijan) az-AZ-BabekNeural2 (Male)
az-AZ-BanuNeural2 (Female)
bg-BG Bulgarian (Bulgaria) bg-BG-BorislavNeural (Male)
bg-BG-KalinaNeural (Female)
bn-BD Bangla (Bangladesh) bn-BD-NabanitaNeural2 (Female)
bn-BD-PradeepNeural2 (Male)
bn-IN Bengali (India) bn-IN-BashkarNeural2 (Male)
bn-IN-TanishaaNeural2 (Female)
bs-BA Bosnian (Bosnia and Herzegovina) bs-BA-GoranNeural2 (Male)
bs-BA-VesnaNeural2 (Female)
ca-ES Catalan (Spain) ca-ES-AlbaNeural (Female)
ca-ES-EnricNeural (Male)
ca-ES-JoanaNeural (Female)
cs-CZ Czech (Czechia) cs-CZ-AntoninNeural (Male)
cs-CZ-VlastaNeural (Female)
cy-GB Welsh (United Kingdom) cy-GB-AledNeural2 (Male)
cy-GB-NiaNeural2 (Female)
da-DK Danish (Denmark) da-DK-ChristelNeural (Female)
da-DK-JeppeNeural (Male)
de-AT German (Austria) de-AT-IngridNeural (Female)
de-AT-JonasNeural (Male)
de-CH German (Switzerland) de-CH-JanNeural (Male)
de-CH-LeniNeural (Female)
de-DE German (Germany) de-DE-AmalaNeural (Female)
de-DE-BerndNeural (Male)
de-DE-ChristophNeural (Male)
de-DE-ConradNeural (Male)
de-DE-ElkeNeural (Female)
de-DE-GiselaNeural (Female, Child)
de-DE-KasperNeural (Male)
de-DE-KatjaNeural (Female)
de-DE-KillianNeural (Male)
de-DE-KlarissaNeural (Female)
de-DE-KlausNeural (Male)
de-DE-LouisaNeural (Female)
de-DE-MajaNeural (Female)
de-DE-RalfNeural (Male)
de-DE-TanjaNeural (Female)
el-GR Greek (Greece) el-GR-AthinaNeural (Female)
el-GR-NestorasNeural (Male)
en-AU English (Australia) en-AU-AnnetteNeural1 (Female)
en-AU-CarlyNeural1 (Female)
en-AU-DarrenNeural1 (Male)
en-AU-DuncanNeural1 (Male)
en-AU-ElsieNeural1 (Female)
en-AU-FreyaNeural1 (Female)
en-AU-JoanneNeural1 (Female)
en-AU-KenNeural1 (Male)
en-AU-KimNeural1 (Female)
en-AU-NatashaNeural (Female)
en-AU-NeilNeural1 (Male)
en-AU-TimNeural1 (Male)
en-AU-TinaNeural1 (Female)
en-AU-WilliamNeural (Male)
en-CA English (Canada) en-CA-ClaraNeural (Female)
en-CA-LiamNeural (Male)
en-GB English (United Kingdom) en-GB-AbbiNeural (Female)
en-GB-AlfieNeural (Male)
en-GB-BellaNeural (Female)
en-GB-ElliotNeural (Male)
en-GB-EthanNeural (Male)
en-GB-HollieNeural (Female)
en-GB-LibbyNeural (Female)
en-GB-MaisieNeural (Female, Child)
en-GB-NoahNeural (Male)
en-GB-OliverNeural (Male)
en-GB-OliviaNeural (Female)
en-GB-RyanNeural1 (Male)
en-GB-SoniaNeural1 (Female)
en-GB-ThomasNeural (Male)
en-HK English (Hong Kong SAR) en-HK-SamNeural (Male)
en-HK-YanNeural (Female)
en-IE English (Ireland) en-IE-ConnorNeural (Male)
en-IE-EmilyNeural (Female)
en-IN English (India) en-IN-NeerjaNeural (Female)
en-IN-PrabhatNeural (Male)
en-KE English (Kenya) en-KE-AsiliaNeural (Female)
en-KE-ChilembaNeural (Male)
en-NG English (Nigeria) en-NG-AbeoNeural (Male)
en-NG-EzinneNeural (Female)
en-NZ English (New Zealand) en-NZ-MitchellNeural (Male)
en-NZ-MollyNeural (Female)
en-PH English (Philippines) en-PH-JamesNeural (Male)
en-PH-RosaNeural (Female)
en-SG English (Singapore) en-SG-LunaNeural (Female)
en-SG-WayneNeural (Male)
en-TZ English (Tanzania) en-TZ-ElimuNeural (Male)
en-TZ-ImaniNeural (Female)
en-US English (United States) en-US-AIGenerate1Neural1 (Male)
en-US-AIGenerate2Neural1 (Female)
en-US-AmberNeural (Female)
en-US-AnaNeural (Female, Child)
en-US-AriaNeural (Female)
en-US-AshleyNeural (Female)
en-US-BrandonNeural (Male)
en-US-ChristopherNeural (Male)
en-US-CoraNeural (Female)
en-US-DavisNeural (Male)
en-US-ElizabethNeural (Female)
en-US-EricNeural (Male)
en-US-GuyNeural (Male)
en-US-JacobNeural (Male)
en-US-JaneNeural (Female)
en-US-JasonNeural (Male)
en-US-JennyMultilingualNeural3 (Female)
en-US-JennyNeural (Female)
en-US-MichelleNeural (Female)
en-US-MonicaNeural (Female)
en-US-NancyNeural (Female)
en-US-RogerNeural1 (Male)
en-US-SaraNeural (Female)
en-US-SteffanNeural (Male)
en-US-TonyNeural (Male)
en-ZA English (South Africa) en-ZA-LeahNeural (Female)
en-ZA-LukeNeural (Male)
es-AR Spanish (Argentina) es-AR-ElenaNeural (Female)
es-AR-TomasNeural (Male)
es-BO Spanish (Bolivia) es-BO-MarceloNeural (Male)
es-BO-SofiaNeural (Female)
es-CL Spanish (Chile) es-CL-CatalinaNeural (Female)
es-CL-LorenzoNeural (Male)
es-CO Spanish (Colombia) es-CO-GonzaloNeural (Male)
es-CO-SalomeNeural (Female)
es-CR Spanish (Costa Rica) es-CR-JuanNeural (Male)
es-CR-MariaNeural (Female)
es-CU Spanish (Cuba) es-CU-BelkysNeural (Female)
es-CU-ManuelNeural (Male)
es-DO Spanish (Dominican Republic) es-DO-EmilioNeural (Male)
es-DO-RamonaNeural (Female)
es-EC Spanish (Ecuador) es-EC-AndreaNeural (Female)
es-EC-LuisNeural (Male)
es-ES Spanish (Spain) es-ES-AbrilNeural1 (Female)
es-ES-AlvaroNeural1 (Male)
es-ES-ArnauNeural1 (Male)
es-ES-DarioNeural1 (Male)
es-ES-EliasNeural1 (Male)
es-ES-ElviraNeural (Female)
es-ES-EstrellaNeural1 (Female)
es-ES-IreneNeural1 (Female)
es-ES-LaiaNeural1 (Female)
es-ES-LiaNeural1 (Female)
es-ES-NilNeural1 (Male)
es-ES-SaulNeural1 (Male)
es-ES-TeoNeural1 (Male)
es-ES-TrianaNeural1 (Female)
es-ES-VeraNeural1 (Female)
es-GQ Spanish (Equatorial Guinea) es-GQ-JavierNeural (Male)
es-GQ-TeresaNeural (Female)
es-GT Spanish (Guatemala) es-GT-AndresNeural (Male)
es-GT-MartaNeural (Female)
es-HN Spanish (Honduras) es-HN-CarlosNeural (Male)
es-HN-KarlaNeural (Female)
es-MX Spanish (Mexico) es-MX-BeatrizNeural (Female)
es-MX-CandelaNeural (Female)
es-MX-CarlotaNeural (Female)
es-MX-CecilioNeural (Male)
es-MX-DaliaNeural (Female)
es-MX-GerardoNeural (Male)
es-MX-JorgeNeural1 (Male)
es-MX-LarissaNeural (Female)
es-MX-LibertoNeural (Male)
es-MX-LucianoNeural (Male)
es-MX-MarinaNeural (Female)
es-MX-NuriaNeural (Female)
es-MX-PelayoNeural (Male)
es-MX-RenataNeural (Female)
es-MX-YagoNeural (Male)
es-NI Spanish (Nicaragua) es-NI-FedericoNeural (Male)
es-NI-YolandaNeural (Female)
es-PA Spanish (Panama) es-PA-MargaritaNeural (Female)
es-PA-RobertoNeural (Male)
es-PE Spanish (Peru) es-PE-AlexNeural (Male)
es-PE-CamilaNeural (Female)
es-PR Spanish (Puerto Rico) es-PR-KarinaNeural (Female)
es-PR-VictorNeural (Male)
es-PY Spanish (Paraguay) es-PY-MarioNeural (Male)
es-PY-TaniaNeural (Female)
es-SV Spanish (El Salvador) es-SV-LorenaNeural (Female)
es-SV-RodrigoNeural (Male)
es-US Spanish (United States) es-US-AlonsoNeural (Male)
es-US-PalomaNeural (Female)
es-UY Spanish (Uruguay) es-UY-MateoNeural (Male)
es-UY-ValentinaNeural (Female)
es-VE Spanish (Venezuela) es-VE-PaolaNeural (Female)
es-VE-SebastianNeural (Male)
et-EE Estonian (Estonia) et-EE-AnuNeural2 (Female)
et-EE-KertNeural2 (Male)
eu-ES Basque eu-ES-AinhoaNeural2 (Female)
eu-ES-AnderNeural2 (Male)
fa-IR Persian (Iran) fa-IR-DilaraNeural2 (Female)
fa-IR-FaridNeural2 (Male)
fi-FI Finnish (Finland) fi-FI-HarriNeural (Male)
fi-FI-NooraNeural (Female)
fi-FI-SelmaNeural (Female)
fil-PH Filipino (Philippines) fil-PH-AngeloNeural2 (Male)
fil-PH-BlessicaNeural2 (Female)
fr-BE French (Belgium) fr-BE-CharlineNeural (Female)
fr-BE-GerardNeural (Male)
fr-CA French (Canada) fr-CA-AntoineNeural (Male)
fr-CA-JeanNeural (Male)
fr-CA-SylvieNeural (Female)
fr-CH French (Switzerland) fr-CH-ArianeNeural (Female)
fr-CH-FabriceNeural (Male)
fr-FR French (France) fr-FR-AlainNeural (Male)
fr-FR-BrigitteNeural (Female)
fr-FR-CelesteNeural (Female)
fr-FR-ClaudeNeural (Male)
fr-FR-CoralieNeural (Female)
fr-FR-DeniseNeural1 (Female)
fr-FR-EloiseNeural (Female, Child)
fr-FR-HenriNeural1 (Male)
fr-FR-JacquelineNeural (Female)
fr-FR-JeromeNeural (Male)
fr-FR-JosephineNeural (Female)
fr-FR-MauriceNeural (Male)
fr-FR-YvesNeural (Male)
fr-FR-YvetteNeural (Female)
ga-IE Irish (Ireland) ga-IE-ColmNeural2 (Male)
ga-IE-OrlaNeural2 (Female)
gl-ES Galician gl-ES-RoiNeural2 (Male)
gl-ES-SabelaNeural2 (Female)
gu-IN Gujarati (India) gu-IN-DhwaniNeural (Female)
gu-IN-NiranjanNeural (Male)
he-IL Hebrew (Israel) he-IL-AvriNeural (Male)
he-IL-HilaNeural (Female)
hi-IN Hindi (India) hi-IN-MadhurNeural (Male)
hi-IN-SwaraNeural (Female)
hr-HR Croatian (Croatia) hr-HR-GabrijelaNeural (Female)
hr-HR-SreckoNeural (Male)
hu-HU Hungarian (Hungary) hu-HU-NoemiNeural (Female)
hu-HU-TamasNeural (Male)
hy-AM Armenian (Armenia) hy-AM-AnahitNeural2 (Female)
hy-AM-HaykNeural2 (Male)
id-ID Indonesian (Indonesia) id-ID-ArdiNeural (Male)
id-ID-GadisNeural (Female)
is-IS Icelandic (Iceland) is-IS-GudrunNeural2 (Female)
is-IS-GunnarNeural2 (Male)
it-IT Italian (Italy) it-IT-BenignoNeural (Male)
it-IT-CalimeroNeural (Male)
it-IT-CataldoNeural (Male)
it-IT-DiegoNeural1 (Male)
it-IT-ElsaNeural (Female)
it-IT-FabiolaNeural (Female)
it-IT-FiammaNeural (Female)
it-IT-GianniNeural (Male)
it-IT-ImeldaNeural (Female)
it-IT-IrmaNeural (Female)
it-IT-IsabellaNeural1 (Female)
it-IT-LisandroNeural (Male)
it-IT-PalmiraNeural (Female)
it-IT-PierinaNeural (Female)
it-IT-RinaldoNeural (Male)
ja-JP Japanese (Japan) ja-JP-AoiNeural1 (Female)
ja-JP-DaichiNeural1 (Male)
ja-JP-KeitaNeural (Male)
ja-JP-MayuNeural1 (Female)
ja-JP-NanamiNeural (Female)
ja-JP-NaokiNeural1 (Male)
ja-JP-ShioriNeural1 (Female)
jv-ID Javanese (Latin, Indonesia) jv-ID-DimasNeural2 (Male)
jv-ID-SitiNeural2 (Female)
ka-GE Georgian (Georgia) ka-GE-EkaNeural2 (Female)
ka-GE-GiorgiNeural2 (Male)
kk-KZ Kazakh (Kazakhstan) kk-KZ-AigulNeural2 (Female)
kk-KZ-DauletNeural2 (Male)
km-KH Khmer (Cambodia) km-KH-PisethNeural2 (Male)
km-KH-SreymomNeural2 (Female)
kn-IN Kannada (India) kn-IN-GaganNeural2 (Male)
kn-IN-SapnaNeural2 (Female)
ko-KR Korean (Korea) ko-KR-BongJinNeural1 (Male)
ko-KR-GookMinNeural1 (Male)
ko-KR-InJoonNeural (Male)
ko-KR-JiMinNeural1 (Female)
ko-KR-SeoHyeonNeural1 (Female)
ko-KR-SoonBokNeural1 (Female)
ko-KR-SunHiNeural (Female)
ko-KR-YuJinNeural1 (Female)
lo-LA Lao (Laos) lo-LA-ChanthavongNeural2 (Male)
lo-LA-KeomanyNeural2 (Female)
lt-LT Lithuanian (Lithuania) lt-LT-LeonasNeural2 (Male)
lt-LT-OnaNeural2 (Female)
lv-LV Latvian (Latvia) lv-LV-EveritaNeural2 (Female)
lv-LV-NilsNeural2 (Male)
mk-MK Macedonian (North Macedonia) mk-MK-AleksandarNeural2 (Male)
mk-MK-MarijaNeural2 (Female)
ml-IN Malayalam (India) ml-IN-MidhunNeural2 (Male)
ml-IN-SobhanaNeural2 (Female)
mn-MN Mongolian (Mongolia) mn-MN-BataaNeural2 (Male)
mn-MN-YesuiNeural2 (Female)
mr-IN Marathi (India) mr-IN-AarohiNeural (Female)
mr-IN-ManoharNeural (Male)
ms-MY Malay (Malaysia) ms-MY-OsmanNeural (Male)
ms-MY-YasminNeural (Female)
mt-MT Maltese (Malta) mt-MT-GraceNeural2 (Female)
mt-MT-JosephNeural2 (Male)
my-MM Burmese (Myanmar) my-MM-NilarNeural2 (Female)
my-MM-ThihaNeural2 (Male)
nb-NO Norwegian Bokmål (Norway) nb-NO-FinnNeural (Male)
nb-NO-IselinNeural (Female)
nb-NO-PernilleNeural (Female)
ne-NP Nepali (Nepal) ne-NP-HemkalaNeural2 (Female)
ne-NP-SagarNeural2 (Male)
nl-BE Dutch (Belgium) nl-BE-ArnaudNeural (Male)
nl-BE-DenaNeural (Female)
nl-NL Dutch (Netherlands) nl-NL-ColetteNeural (Female)
nl-NL-FennaNeural1 (Female)
nl-NL-MaartenNeural1 (Male)
pl-PL Polish (Poland) pl-PL-AgnieszkaNeural (Female)
pl-PL-MarekNeural (Male)
pl-PL-ZofiaNeural (Female)
ps-AF Pashto (Afghanistan) ps-AF-GulNawazNeural2 (Male)
ps-AF-LatifaNeural2 (Female)
pt-BR Portuguese (Brazil) pt-BR-AntonioNeural (Male)
pt-BR-BrendaNeural (Female)
pt-BR-DonatoNeural (Male)
pt-BR-ElzaNeural (Female)
pt-BR-FabioNeural (Male)
pt-BR-FranciscaNeural (Female)
pt-BR-GiovannaNeural (Female)
pt-BR-HumbertoNeural (Male)
pt-BR-JulioNeural (Male)
pt-BR-LeilaNeural (Female)
pt-BR-LeticiaNeural (Female)
pt-BR-ManuelaNeural (Female)
pt-BR-NicolauNeural (Male)
pt-BR-ValerioNeural (Male)
pt-BR-YaraNeural (Female)
pt-PT Portuguese (Portugal) pt-PT-DuarteNeural (Male)
pt-PT-FernandaNeural (Female)
pt-PT-RaquelNeural (Female)
ro-RO Romanian (Romania) ro-RO-AlinaNeural (Female)
ro-RO-EmilNeural (Male)
ru-RU Russian (Russia) ru-RU-DariyaNeural (Female)
ru-RU-DmitryNeural (Male)
ru-RU-SvetlanaNeural (Female)
si-LK Sinhala (Sri Lanka) si-LK-SameeraNeural2 (Male)
si-LK-ThiliniNeural2 (Female)
sk-SK Slovak (Slovakia) sk-SK-LukasNeural (Male)
sk-SK-ViktoriaNeural (Female)
sl-SI Slovenian (Slovenia) sl-SI-PetraNeural (Female)
sl-SI-RokNeural (Male)
so-SO Somali (Somalia) so-SO-MuuseNeural2 (Male)
so-SO-UbaxNeural2 (Female)
sq-AL Albanian (Albania) sq-AL-AnilaNeural2 (Female)
sq-AL-IlirNeural2 (Male)
sr-RS Serbian (Cyrillic, Serbia) sr-RS-NicholasNeural2 (Male)
sr-RS-SophieNeural2 (Female)
su-ID Sundanese (Indonesia) su-ID-JajangNeural2 (Male)
su-ID-TutiNeural2 (Female)
sv-SE Swedish (Sweden) sv-SE-HilleviNeural (Female)
sv-SE-MattiasNeural (Male)
sv-SE-SofieNeural (Female)
sw-KE Swahili (Kenya) sw-KE-RafikiNeural2 (Male)
sw-KE-ZuriNeural2 (Female)
sw-TZ Swahili (Tanzania) sw-TZ-DaudiNeural (Male)
sw-TZ-RehemaNeural (Female)
ta-IN Tamil (India) ta-IN-PallaviNeural (Female)
ta-IN-ValluvarNeural (Male)
ta-LK Tamil (Sri Lanka) ta-LK-KumarNeural (Male)
ta-LK-SaranyaNeural (Female)
ta-MY Tamil (Malaysia) ta-MY-KaniNeural (Female)
ta-MY-SuryaNeural (Male)
ta-SG Tamil (Singapore) ta-SG-AnbuNeural (Male)
ta-SG-VenbaNeural (Female)
te-IN Telugu (India) te-IN-MohanNeural (Male)
te-IN-ShrutiNeural (Female)
th-TH Thai (Thailand) th-TH-AcharaNeural (Female)
th-TH-NiwatNeural (Male)
th-TH-PremwadeeNeural (Female)
tr-TR Turkish (Turkey) tr-TR-AhmetNeural (Male)
tr-TR-EmelNeural (Female)
uk-UA Ukrainian (Ukraine) uk-UA-OstapNeural (Male)
uk-UA-PolinaNeural (Female)
ur-IN Urdu (India) ur-IN-GulNeural (Female)
ur-IN-SalmanNeural (Male)
ur-PK Urdu (Pakistan) ur-PK-AsadNeural (Male)
ur-PK-UzmaNeural (Female)
uz-UZ Uzbek (Latin, Uzbekistan) uz-UZ-MadinaNeural2 (Female)
uz-UZ-SardorNeural2 (Male)
vi-VN Vietnamese (Vietnam) vi-VN-HoaiMyNeural (Female)
vi-VN-NamMinhNeural (Male)
wuu-CN Chinese (Wu, Simplified) wuu-CN-XiaotongNeural1,2 (Female)
wuu-CN-YunzheNeural1,2 (Male)
yue-CN Chinese (Cantonese, Simplified) yue-CN-XiaoMinNeural1,2 (Female)
yue-CN-YunSongNeural1,2 (Male)
zh-CN Chinese (Mandarin, Simplified) zh-CN-XiaochenNeural (Female)
zh-CN-XiaohanNeural (Female)
zh-CN-XiaomengNeural (Female)
zh-CN-XiaomoNeural (Female)
zh-CN-XiaoqiuNeural (Female)
zh-CN-XiaoruiNeural (Female)
zh-CN-XiaoshuangNeural (Female, Child)
zh-CN-XiaoxiaoNeural (Female)
zh-CN-XiaoxuanNeural (Female)
zh-CN-XiaoyanNeural (Female)
zh-CN-XiaoyiNeural (Female)
zh-CN-XiaoyouNeural (Female, Child)
zh-CN-XiaozhenNeural (Female)
zh-CN-YunfengNeural (Male)
zh-CN-YunhaoNeural (Male)
zh-CN-YunjianNeural (Male)
zh-CN-YunxiaNeural (Male)
zh-CN-YunxiNeural (Male)
zh-CN-YunyangNeural (Male)
zh-CN-YunyeNeural (Male)
zh-CN-YunzeNeural (Male)
zh-CN-henan Chinese (Zhongyuan Mandarin Henan, Simplified) zh-CN-henan-YundengNeural2 (Male)
zh-CN-liaoning Chinese (Northeastern Mandarin, Simplified) zh-CN-liaoning-XiaobeiNeural1,2 (Female)
zh-CN-shaanxi Chinese (Zhongyuan Mandarin Shaanxi, Simplified) zh-CN-shaanxi-XiaoniNeural1,2 (Female)
zh-CN-shandong Chinese (Jilu Mandarin, Simplified) zh-CN-shandong-YunxiangNeural2 (Male)
zh-CN-sichuan Chinese (Southwestern Mandarin, Simplified) zh-CN-sichuan-YunxiNeural1,2 (Male)
zh-HK Chinese (Cantonese, Traditional) zh-HK-HiuGaaiNeural (Female)
zh-HK-HiuMaanNeural (Female)
zh-HK-WanLungNeural1 (Male)
zh-TW Chinese (Taiwanese Mandarin, Traditional) zh-TW-HsiaoChenNeural (Female)
zh-TW-HsiaoYuNeural (Female)
zh-TW-YunJheNeural (Male)
zu-ZA Zulu (South Africa) zu-ZA-ThandoNeural2 (Female)
zu-ZA-ThembaNeural2 (Male)"""

voices_map = input_to_map(input_str)
print(voices_map)